apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    owner: frodo-baggins
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
